site_name: HBCD Processing and Analytic Software Standards
theme: readthedocs
markdown_extensions:
  - pymdownx.tasklist
extra_css:
  - css/extra.css 
plugins:
  - search
docs_dir: docs
nav:
  - Home: index.md
